version: "3"

tasks:
  help:
    cmds:
      - echo "Use ./mono <command> [flags]"

  bootstrap:
    cmds:
      - bash -c 'set -euo pipefail; if ! command -v task >/dev/null 2>&1; then install_dir=/usr/local/bin; if [ ! -w "$install_dir" ]; then install_dir="$HOME/.local/bin"; mkdir -p "$install_dir"; fi; curl -sL https://taskfile.dev/install.sh | sh -s -- -d -b "$install_dir"; fi; pnpm install'

  fmt:
    cmds:
      - ./mono fmt

  lint:
    cmds:
      - ./mono lint

  typecheck:
    cmds:
      - ./mono typecheck

  test:
    cmds:
      - ./mono test

  build:
    cmds:
      - ./mono build

  check:
    cmds:
      - ./mono check

  contracts:lint:
    cmds:
      - ./mono contracts:lint

  contracts:breaking:
    cmds:
      - ./mono contracts:breaking

  contracts:build:
    cmds:
      - ./mono contracts:build

  docs:lint:
    cmds:
      - ./mono docs:lint

  docs:build:
    cmds:
      - ./mono docs:build

  docs:serve:
    cmds:
      - ./mono docs:serve

  infra:up:
    cmds:
      - ./mono infra:up

  infra:down:
    cmds:
      - ./mono infra:down

  list:ports:
    cmds:
      - ./mono list ports

  list:scopes:
    cmds:
      - ./mono list scopes

  doctor:
    cmds:
      - ./mono doctor

  new:app:
    cmds:
      - ./mono new app {{.CLI_ARGS}}

  new:service:
    cmds:
      - ./mono new service {{.CLI_ARGS}}

  new:lib:
    cmds:
      - ./mono new lib {{.CLI_ARGS}}

  new:package:
    cmds:
      - ./mono new package {{.CLI_ARGS}}

  tooling:test:
    cmds:
      - ./mono tooling test

  tooling:test:e2e:
    cmds:
      - ./mono tooling test --e2e

  db:migrate:
    cmds:
      - 'echo "Database migration task"'
      - 'echo "Usage: ./mono --scope back/services/<service> db:migrate"'
      - 'echo "This will run flyway:migrate or equivalent migration tool for the specified service"'

  deps:graph:
    cmds:
      - mkdir -p reports/deps
      - echo "Generating frontend dependency graph..."
      - bash -c 'if pnpm -r --filter ./front... exec -- npx --yes madge --version >/dev/null 2>&1; then pnpm -r --filter ./front... exec -- npx madge --image reports/deps/frontend.png --extensions js,ts,tsx; else echo "Madge not installed, skipping frontend graph"; fi'
      - echo "Generating backend dependency tree..."
      - bash -c 'set -o pipefail && mvn -f back/pom.xml dependency:tree > reports/deps/backend.txt || { echo "Maven dependency tree generated (may have warnings)"; exit 0; }'
      - echo "Dependency reports generated in reports/deps/"
