version: "3"

tasks:
  help:
    cmds:
      - echo "Use ./mono <command> [flags]"

  bootstrap:
    cmds:
      - bash -c 'set -euo pipefail; if ! command -v task >/dev/null 2>&1; then install_dir=/usr/local/bin; if [ ! -w "$install_dir" ]; then install_dir="$HOME/.local/bin"; mkdir -p "$install_dir"; fi; curl -sL https://taskfile.dev/install.sh | sh -s -- -d -b "$install_dir"; fi; pnpm install'

  fmt:
    cmds:
      - pnpm biome format --write .
      - mvn -f back/pom.xml -q com.diffplug.spotless:spotless-maven-plugin:2.44.0:apply

  lint:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/lint && pnpm biome lint . | tee reports/lint/biome.log'
      - bash -c 'set -o pipefail && mvn -f back/pom.xml -q com.diffplug.spotless:spotless-maven-plugin:2.44.0:check | tee reports/lint/spotless.log'
      - bash -c 'set -o pipefail && mvn -f back/pom.xml -q -DskipTests compile com.github.spotbugs:spotbugs-maven-plugin:4.8.6.0:check -Dspotbugs.effort=Default -Dspotbugs.threshold=Medium -Dspotbugs.excludeFilterFile=config/spotbugs/excludes.xml | tee reports/lint/spotbugs.log'
      - bash -c 'set -o pipefail && pnpm spectral lint --ruleset contracts/rules/spectral.yaml contracts/rest/*.openapi.yaml | tee reports/lint/spectral.log'
      - bash -c 'set -o pipefail && pnpm markdownlint-cli2 "docs/**/*.md" "README.md" | tee reports/lint/markdown.log'

  typecheck:
    cmds:
      - mkdir -p reports/typecheck && pnpm -r --filter ./front... tsc --noEmit | tee reports/typecheck/front-tsc.log

  test:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/test && mvn -f back/pom.xml test | tee reports/test/maven.log'
      - bash -c 'set -o pipefail && rm -rf reports/vitest && mkdir -p reports/vitest && pnpm vitest run --reporter=junit --outputFile=reports/vitest/root.junit.xml | tee reports/vitest/vitest.log'

  build:
    cmds:
      - bash -c 'set -o pipefail && rm -rf reports/build && mkdir -p reports/build && mvn -f back/pom.xml -DskipTests package | tee reports/build/maven.log'
      - bash -c 'set -o pipefail && pnpm -r --filter ./front... build | tee reports/build/front-build.log'

  check:
    deps: [lint, typecheck, test, build]

  contracts:lint:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/contracts && pnpm spectral lint --ruleset contracts/rules/spectral.yaml contracts/rest/*.openapi.yaml | tee reports/contracts/spectral.log'

  contracts:breaking:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/contracts && node tools/contracts/breaking.mjs | tee reports/contracts/breaking.log'

  contracts:build:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/contracts && node tools/contracts/bundle-all.mjs | tee reports/contracts/bundle-all.log'
      - bash -c 'set -o pipefail && node tools/contracts/gen-clients.mjs | tee reports/contracts/gen-clients.log'
      - bash -c 'set -o pipefail && pnpm -r --filter ./front... typecheck | tee reports/contracts/typecheck.log'

  docs:lint:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/docs && pnpm markdownlint-cli2 "docs/**/*.md" "README.md" | tee reports/docs/markdownlint.log'

  docs:build:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/docs && node tools/contracts/bundle-all.mjs | tee reports/docs/bundle-all.log'
      - bash -c 'set -o pipefail && node tools/contracts/gen-clients.mjs | tee reports/docs/gen-clients.log'
      - bash -c 'set -o pipefail && pnpm -C docs/site run build | tee reports/docs/vitepress-build.log'

  docs:serve:
    cmds:
      - mkdir -p reports/docs
      - bash -c 'pnpm -C docs/site run dev 2>&1 | tee reports/docs/vitepress-dev.log'

  infra:up:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/infra && USER_ID=$(id -u) GROUP_ID=$(id -g) docker compose -f infra/tools.compose.yaml up -d | tee reports/infra/up.log'

  infra:down:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/infra && USER_ID=$(id -u) GROUP_ID=$(id -g) docker compose -f infra/tools.compose.yaml down --remove-orphans | tee reports/infra/down.log'

  list:ports:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/list && node tools/scaffold/ports.cjs list | tee reports/list/ports.log'

  list:scopes:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/list && node tools/list-scopes.mjs | tee reports/list/scopes.log'

  doctor:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/doctor && node tools/tooling/doctor.mjs | tee reports/doctor/tooling.log && node tools/scaffold/ports.cjs doctor | tee reports/doctor/ports.log'

  new:app:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/new && node tools/scaffold/actions/app.cjs {{.CLI_ARGS}} | tee reports/new/app.log'

  new:service:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/new && node tools/scaffold/actions/service.cjs {{.CLI_ARGS}} | tee reports/new/service.log'

  new:lib:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/new && node tools/scaffold/actions/lib.cjs {{.CLI_ARGS}} | tee reports/new/lib.log'

  new:package:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/new && node tools/scaffold/actions/package.cjs {{.CLI_ARGS}} | tee reports/new/package.log'

  delete:app:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/delete && node tools/scaffold/actions/delete-app.cjs {{.CLI_ARGS}} | tee reports/delete/app.log'

  delete:service:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/delete && node tools/scaffold/actions/delete-service.cjs {{.CLI_ARGS}} | tee reports/delete/service.log'

  delete:lib:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/delete && node tools/scaffold/actions/delete-lib.cjs {{.CLI_ARGS}} | tee reports/delete/lib.log'

  delete:package:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/delete && node tools/scaffold/actions/delete-package.cjs {{.CLI_ARGS}} | tee reports/delete/package.log'

  tooling:test:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/tooling && pnpm vitest run | tee reports/tooling/vitest.log'

  tooling:test:e2e:
    cmds:
      - bash -c 'set -o pipefail && mkdir -p reports/tooling && pnpm vitest run --dir tools/test/e2e | tee reports/tooling/vitest-e2e.log'

  db:migrate:
    cmds:
      - 'echo "Database migration task"'
      - 'echo "Usage: ./mono --scope back/services/<service> db:migrate"'
      - 'echo "This will run flyway:migrate or equivalent migration tool for the specified service"'

  deps:graph:
    cmds:
      - mkdir -p reports/deps
      - echo "Generating frontend dependency graph..."
      - bash -c 'if pnpm -r --filter ./front... exec -- npx --yes madge --version >/dev/null 2>&1; then pnpm -r --filter ./front... exec -- npx madge --image reports/deps/frontend.png --extensions js,ts,tsx; else echo "Madge not installed, skipping frontend graph"; fi'
      - echo "Generating backend dependency tree..."
      - bash -c 'set -o pipefail && mvn -f back/pom.xml dependency:tree > reports/deps/backend.txt || { echo "Maven dependency tree generated (may have warnings)"; exit 0; }'
      - echo "Dependency reports generated in reports/deps/"
